---
name: Pod-PseudoPod
version: 0.15
author:
  - "Allison Randal (allison@perl.org)"
abstract: A framework for parsing PseudoPod
license: perl
requires:
  HTML::Entities: 0
  Pod::Simple: 3.02
  Text::Wrap: 98.112902
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Pod::PseudoPod:
    file: lib/Pod/PseudoPod.pm
    version: 0.15
  Pod::PseudoPod::Checker:
    file: lib/Pod/PseudoPod/Checker.pm
    version: 0.11
  Pod::PseudoPod::DocBook:
    file: lib/Pod/PseudoPod/DocBook.pm
    version: 0.15
  Pod::PseudoPod::DumpAsXML:
    file: lib/Pod/PseudoPod/DumpAsXML.pm
    version: 1.01
  Pod::PseudoPod::HTML:
    file: lib/Pod/PseudoPod/HTML.pm
    version: 0.12
  Pod::PseudoPod::Index:
    file: lib/Pod/PseudoPod/Index.pm
    version: 0.11
  Pod::PseudoPod::Text:
    file: lib/Pod/PseudoPod/Text.pm
    version: 0.11
  Pod::PseudoPod::XMLOutStream:
    file: lib/Pod/PseudoPod/XMLOutStream.pm
    version: 1.02
resources:
  license: http://dev.perl.org/licenses/
