=pod

=head0 Chapter Title

This is a sample PseudoPod document. It includes most of the
formatting elements added to O'Reilly's PseudoPod, and a few familiar
ones from ordinary Pod.

=head1 For Directives

At the moment, Pod::PseudoPod handles two types of =for directives,
the standard Pod style with no =end directive, and the PseudoPod style
with an =end directive.

=head2 For without End

Without and =end directive, all the content in a =for must be in a
single paragraph, and that paragraph immediately follows the =for (it
cannot be separated by a blank line).

=for editor
This is the content of the for.

=head2 For with End

With an end directive, you can have multiple paragraphs. These must be
separated from the =for by at least one blank line.

=for editor

This is some content of the for.

This is more content of the for.

=end

=head1 Begin/End Directives

Tables, sidebars, and figures are handled specially, all other
begin/end pairs are simply treated as ordinary text. In the html
formatter, if the "add_css_tags" option is turned on each is wrapped
in a div tag with the class set to the target ("=begin comment" is a
div with class='comment') so you can format them however you like. A
default set of formats in included in the sample style.css.

=head2 Program listings

=begin programlisting

  Used for code blocks.
  They don't have any impact
  on text format (code still
  has to be indented).

=end programlisting

=head2 Epigraphs

=begin epigraph

This is a sample epigraph. These are generally italic, and often
aligned right.

=end epigraph

=head2 Tables


=begin table picture Example Table Title

=headrow

=row

=cell Head 1

=cell Head 2

=bodyrows

=row

=cell Some content for the first cell.

=cell Some content for the second cell.

=end table


=head2 Figures

F codes within figures are converted into image source tags in html.

=begin figure

Z<some cross-reference>

F<image.gif>

=end figure

=cut
