#!/usr/bin/perl

######################################################################
#
# A sample PseudoPod to HTML converter script that uses
# Pod::PseudoPod::HTML.
#
# usage:
#
# ./pod2html filename.pod > filename.html
#
######################################################################

use lib "../lib";
use Pod::PseudoPod::HTML;

my $file = $ARGV[0];
my $parser  = Pod::PseudoPod::HTML->new ();
$parser->add_body_tags(1);
$parser->add_css_tags(1);

if (-e $file) {
  $parser->parse_file($file)->any_errata_seen;
} else {
  die "Unable to open file\n";
}

exit;
